language: go
go:
 - 1.5.3
 - 1.6.3
 - 1.7
 - tip

script:
 - go test -v -race -parallel 5 -coverprofile=coverage.txt -covermode=atomic ./
 - go test github.com/fortytw2/leaktest -run ^TestEmptyLeak$

before_install:
  - pip install --user codecov
after_success:
  - codecov
